### PR TITLE
completed MemoryType

### PR DESCRIPTION
**Pull request by sduverger**

### CODE REVIEW

**Comment by sduverger** [comment]
Hi,

Do you plan to merge it one day ?

Regards :)

**Comment by gz** [comment]
Hey Stephane, Sorry I ignored you for so long things are pretty busy atm for me. But this looks great, many thanks!

**Comment by gz** [comment]
Published crate as version 0.3.0

**Comment by sduverger** [comment]
No problem you're welcome. I'm happy to contribute to your code. Many
thanks to you.
I'm writing an hypervisor in rust. Your crate is very useful to me.

2017-09-20 12:37 GMT+02:00 Gerd Zellweger <notifications@github.com>:

**Pull request merged**
