### PR TITLE
Add some functionality for using this in bootloaders

### PR DESCRIPTION
**Pull request by YtvwlD**
I wrote this code after opening #7.

This moves the current code into a new `information` module (but `pub use`s are there, so existing code should be fine) and adds a new module called `header` that's able to parse a Multiboot header contained in a executable.

Also, the `Multiboot` struct has setters to modify the contents and implements `Default`.

I consider this a draft because while it works for me, there are a few things where I'm unsure about:

### the initial creation of the structs

The `Multiboot` struct doesn't own the `MultibootInfo` struct, but it contains all the methods. So creating requires calling `MultibootInfo::default()` first to attain ownership and then `Multiboot::from_ref` to use it. This works, but doesn't really feel right, I don't know.

### addressing

I'm operating in an environment where logical addresses are physical addresses – both for me and for the kernel.
I might have missing address translations, I'm not sure.

### allocating / abstracting / memory leaks

Some fields contain pointers (eg. the strings or the modules). My code isn't really consistent in what happens:
 * cmdline and boot loader name are taking Rust `&str`s and an allocation function, then create C strings by copying the bytes to newly allocated memory
 * modules take a `&[Module]` reference and an allocation function, then create an array of `MBModule`s
 * memory maps take a `&'static [MemoryEntry]`
 * symbols take the number and size of symbol header entries and *a pointer to a slice containing the actual symbol header*

The last one feels just incredibly unsafe, but the first two allocate memory in a hacky way and just leak it if they are called twice.
If you have any suggestions on how to do this in a uniform way, I'd be very happy to take them.

### some functionality is still missing

I didn't add full support for AOut and stuff that only works on legacy BIOSes (eg. APM or VBE), because I don't have a use for that. If you think it would still make sense to have that functionality, I could add that.

### documentation and tests

I added some documentation, but not enough. And I didn't add any tests, yet. If you agree on the general design, I'd like to do that later.

### CODE REVIEW

**Comment by gz** [comment]
> I wrote this code after opening #7.
Many thanks for giving this crate some love, it is highly appreciated.

> ### the initial creation of the structs
> 
> The `Multiboot` struct doesn't own the `MultibootInfo` struct, but it contains all the methods. So creating requires calling `MultibootInfo::default()` first to attain ownership and then `Multiboot::from_ref` to use it. This works, but doesn't really feel right, I don't know.

I didn't see a Default implementation for `MultibootInfo` so not sure where you're getting it from, most likely by casting a raw address? In this case `Multiboot::new()` wouldn't work?

> ### addressing
> 
> I'm operating in an environment where logical addresses are physical addresses – both for me and for the kernel.
> I might have missing address translations, I'm not sure.
Yes not much we can do here (besides from adding elaborate testing). But if anyone runs this without identity mapping, they can always report new issues.

> ### allocating / abstracting / memory leaks
> 
> Some fields contain pointers (eg. the strings or the modules). My code isn't really consistent in what happens:
> 
>     * cmdline and boot loader name are taking Rust `&str`s and an allocation function, then create C strings by copying the bytes to newly allocated memory
> 
>     * modules take a `&[Module]` reference and an allocation function, then create an array of `MBModule`s
> 
>     * memory maps take a `&'static [MemoryEntry]`
> 
>     * symbols take the number and size of symbol header entries and _a pointer to a slice containing the actual symbol header_
> 
> 
> The last one feels just incredibly unsafe, but the first two allocate memory in a hacky way and just leak it if they are called twice.
> If you have any suggestions on how to do this in a uniform way, I'd be very happy to take them.

This is an interesting use-case where you're allowing to set the Multiboot information too. Curious what you're using the crate for? I always imagined if someone wants to generate a multiboot compatible memory layout it might be best to just have a serialization approach  that emits the right byte sequences. But in general I think what you did seems fine for now. Most likely 99% of the users won't ever use these features anyways.

> ### some functionality is still missing
> 
> I didn't add full support for AOut and stuff that only works on legacy BIOSes (eg. APM or VBE), because I don't have a use for that. If you think it would still make sense to have that functionality, I could add that.

Yes I am also not really using any of this or am aware of anyone wanting this so feel free to ignore it.

> ### documentation and tests
> 
> I added some documentation, but not enough. And I didn't add any tests, yet. If you agree on the general design, I'd like to do that later.

Yes sounds good to me. Let me know if you want to merge this as is for now and release a new version or you want to first improve docs/tests?

**Comment by YtvwlD** [comment]
That sounds good. And first, sorry for the delay.

> I didn't see a Default implementation for MultibootInfo

I did add `#[derive(Default)]` to  `MultibootInfo` in 0ea36d3c to create an empty struct with no flags set and almost everything set to zero.

> This is an interesting use-case where you're allowing to set the Multiboot information too. Curious what you're using the crate for?

I'm writing a bootloader for Multiboot-compatible kernels (in Rust, obviously).

> Let me know if you want to merge this as is for now and release a new version or you want to first improve docs/tests?

I did have an idea on how to improve and unify the allocation/addressing stuff which I hope to get done this weekend, so it would be nice if this could be in the new version (else the API would change twice). I'm not sure on whether I get docs and tests done, too, so let's see?

**Comment by gz** [comment]
Sounds good, let me know if I should merge this in master and you want to make a new PR or if I should keep this open.

**Comment by YtvwlD** [comment]
Please keep this open, I'll just add new commits.

So about the memory allocation: In cf93bd442e459c5c16fe5775c538fc548154f224 I've added a new trait which encompasses `paddr_to_slice` and `alloc_func`:

```rust
pub trait MemoryManagement {
    unsafe fn paddr_to_slice(&self, addr: PAddr, length: usize) -> Option<&'static [u8]>;
    unsafe fn allocate(&mut self, length: usize) -> Option<(PAddr, &mut [u8])>;
    unsafe fn deallocate(&mut self, addr: PAddr);
}
```

This should solve the problems with memory mapping and memory leaks in the original PR.

As I've broken the API compatibility, I've decided to remove the `pub use`s in the main module.

So, code using this has to change its imports a bit (from `use multiboot::foo` to `use multiboot::information::foo`) and implement `MemoryManagement` (at least the `paddr_to_slice` method).

If that's too destructive for your taste I can drop this change, but I feel like changes to applications would be small and it would make the code more readable.

To compensate this a bit, I added more documentation in 97154d44787f2805113f571e7b2609296f279025. I *think* that's enough, but if you have any questions I'd be happy to add additional comments.

I plan on adding tests tomorrow.

## allocation, pointers and leaks in detail

There are now only two possible options to set fields containing a pointer. Some are both at once, eg. a module references both a piece of memory and contains a string.

### copying and allocating or freeing

This happens when the passed data has to be changed, eg. when passing strings.
The library uses `MemoryManagement` to allocate and free the memory as needed.

### passing a pointer

This happens when the passed data can be used verbatim, eg. ELF symbols.
The calling application is reponsible for making sure that the pointer is valid.

**Comment by YtvwlD** [comment]
So, I've added tests for reading a header and both reading and writing an information struct. I fixed about two small issues I encountered when writing these tests.

I think this PR is finally good to go, but if you spot an error, please let me know.

**Comment by gz** [comment]
Great, thank you for all the work!

**Comment by gz** [comment]
Released as 0.6.0

**Pull request merged**
