### PR TITLE
[FIX] change type of PAddr to work on the x86 (32bit machine)

### PR DESCRIPTION
**Pull request by mopp**
Hello
Thank you for your very useful library.
I would like to use this crate in my OS [Axel](https://github.com/mopp/Axel/tree/rusty)
Unfortunately my OS can only work on x86_32.
But, I found that simple modification make this crate work in x86_32 OS.
Then, I created this pull request.
Thanks.

### CODE REVIEW

**Comment by gz** [comment]
Many thanks for submitting this pull request.

I am struggling a bit to have a good solution for what the correct PAddr type is here... Ideally it would simply be 32bit on x86-32 and 64bit on x86-64. However, even on 32bit with PAE there are 36 physical address bits (altough that is probably not supported by multiboot). Also maybe we want to make this consistent with @dschatzbergs patch to the x86 library (gz/rust-x86#6), but that may be overkill for just the multiboot lib.
IMHO usize is technically not correct as it is defined to be the size of the virtual address space. So maybe it should just be u64/u32 depending on the architecture you are running on. Toughts?

**Comment by gz** [comment]
Many thanks for submitting this pull request.

I am struggling a bit to have a good solution for what the correct PAddr type is here... Ideally it would simply be 32bit on x86-32 and 64bit on x86-64. However, even on 32bit with PAE there are 36 physical address bits (altough that is probably not supported by multiboot). Also maybe we want to make this consistent with @dschatzberg erg patch to the x86 library (gz/rust-x86#6), but that may be overkill for just the multiboot lib.
IMHO usize is technically not correct as it is defined to be the size of the virtual address space. So maybe it should just be u64/u32 depending on the architecture you are running on. Toughts?

**Comment by mopp** [comment]
Thanks for your response, I understood this problem and agree with your mention about the size of usize.
And I'm sorry for forgetting 32bit with PAE.
I may have to use u64 instead of usize in my project.
Also, this pull request will be closed.

PS
After writing first pull request comment, I found your great library [gz/rust-x86](https://github.com/gz/rust-x86)
I consider that changing my OS architecture...

**Comment by gz** [comment]
Hi @mopp, let's not close it just yet ;). I think I can at least merge the change about the u32 for the signature, I will look at the multboot spec in more detail over the weekend to see if there is any stronger guarantees about the addresses in there!

**Comment by mopp** [comment]
Hi
Ok, I will keep this.

Many thanks.

**Comment by dschatzberg** [comment]
@gz @mopp I think PAddr should always be 64-bit due to PAE. It seems reasonable to get the definition from rust-x86. The dependency doesn't really have any downsides except compile time (maybe that's something to fix with rust-x86 though). It's nice to have one place where these types are defined and anyone doing OS work can depend on a well-used crate.

**Comment by gz** [comment]
@dschatzberg I agree, initially I had a dependency in multiboot on x86 but then I figured I would drop it because the only thing I depended upon was the PAddr and VAddr types, but I don't see a big issue with adding x86 back as a dependency.

I hear you on compile time for the x86 crate. The perfom counters parsing in build.rs is the culprit here. I believe that there is now an option to specify dependencies for build.rs such that it does not run everytime. That may solve the problem. Alternatively I will factor out the perfmon data in a separate crate.

**Pull request closed without merging**
